description: >
  Install conan and configure it.
parameters:
  conan-config-version:
    type: string
    default: "3.1.0"
  pip:
    type: string
    default: "pip3"
steps:
  - run:
      name: Install Conan
      command: << parameters.pip >> install --upgrade conan
  - run:
      name: Config conan
      command: npm install @vernier/conan-config@<< parameters.conan-config-version >>
  - run:
      name: Add conan remote and user
      command: |
        conan user gitlab+deploy-token-296862 -p $GITLAB_API_KEY -r vst-libs
        conan user gitlab+deploy-token-296862 -p $GITLAB_API_KEY -r gitlab
